

spring:
  # 数据源配置
  datasource:
    username: root
    password: 1qaz2wsx
    url: jdbc:mysql://127.0.0.1:3306/gulimall_ums?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    # mysql8版本以上驱动包指定新的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  # mapper文件路径
  mapper-locations: classpath:/mapper/**/*.xml
server:
  port: 8000
