server:
  port: 10000

spring:
  application:
    name: mall-product
  # 数据源配置
  datasource:
    username: root
    password: 1qaz2wsx
    url: jdbc:mysql://127.0.0.1:3306/gulimall_pms?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    # mysql8版本以上驱动包指定新的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 服务注册中心地址
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  # 指定日期格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  redis:
    host: 127.0.0.1
    port: 6379
    password: 1qaz2wsx

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  # mapper文件路径
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    com.example.mallproduct.dao: debug
